import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nabvar } from "./components/nabvar";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" -z-50 fixed w-full h-full">
          <Image src={"/poke.jpg"} layout="fill" alt="imag"  />
        </div>
        <Nabvar />
        {children}
      </body>
    </html>
  );
}
